name: Build Sonnenhaus-Webapp
run-name: ${{ github.actor }}
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Prepare nodejs
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Prepare dependencies
        run: npm install
      - name: Build App
        run: npm run build_prod
      - name: Package build
        run: tar -cvf release.tar ./dist
      - name: Create Release
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Upload Release
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.tar
          asset_name: release.tar
          asset_content_type: application/xtar
