name: Build Sonnenhaus-Webapp
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Prepare nodejs
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Prepare dependencies
        run: npm install
      - name: Build App
        run: npm run build_prod
      - name: Package build
        run: tar -cvf release.tar ./dist
      - name: Calculate Release tag
        id: vars
        run: echo "release_tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.release_tag }}
          files: ./release.tar
